// Generated by gencpp from file tracking_module/DetectedObjectList.msg
// DO NOT EDIT!


#ifndef TRACKING_MODULE_MESSAGE_DETECTEDOBJECTLIST_H
#define TRACKING_MODULE_MESSAGE_DETECTEDOBJECTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tracking_module/DetectedObject.h>

namespace tracking_module
{
template <class ContainerAllocator>
struct DetectedObjectList_
{
  typedef DetectedObjectList_<ContainerAllocator> Type;

  DetectedObjectList_()
    : header()
    , objects()  {
    }
  DetectedObjectList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tracking_module::DetectedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tracking_module::DetectedObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::tracking_module::DetectedObjectList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracking_module::DetectedObjectList_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObjectList_

typedef ::tracking_module::DetectedObjectList_<std::allocator<void> > DetectedObjectList;

typedef boost::shared_ptr< ::tracking_module::DetectedObjectList > DetectedObjectListPtr;
typedef boost::shared_ptr< ::tracking_module::DetectedObjectList const> DetectedObjectListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracking_module::DetectedObjectList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracking_module::DetectedObjectList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracking_module::DetectedObjectList_<ContainerAllocator1> & lhs, const ::tracking_module::DetectedObjectList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracking_module::DetectedObjectList_<ContainerAllocator1> & lhs, const ::tracking_module::DetectedObjectList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracking_module

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_module::DetectedObjectList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_module::DetectedObjectList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_module::DetectedObjectList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aa28ce16652a784162874bcf0ae26ca";
  }

  static const char* value(const ::tracking_module::DetectedObjectList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aa28ce16652a784ULL;
  static const uint64_t static_value2 = 0x162874bcf0ae26caULL;
};

template<class ContainerAllocator>
struct DataType< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracking_module/DetectedObjectList";
  }

  static const char* value(const ::tracking_module::DetectedObjectList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"DetectedObject[] objects\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tracking_module/DetectedObject\n"
"string sample_token\n"
"float64[] translation\n"
"float64[] size\n"
"float64[] rotation\n"
"float64[] velocity\n"
"string detection_name\n"
"float64 detection_score\n"
"string attribute_name\n"
;
  }

  static const char* value(const ::tracking_module::DetectedObjectList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObjectList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracking_module::DetectedObjectList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracking_module::DetectedObjectList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tracking_module::DetectedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKING_MODULE_MESSAGE_DETECTEDOBJECTLIST_H
